name: giphy 🌈

on: pull_request

jobs:
  pRStatusGiphy:
    name: PR Status Giphy
    runs-on: ubuntu-latest
    steps:
    - name: PR Status Giphy
      uses: jzweifel/pr-status-giphy-action@master
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}